= Knative Client
:experimental: true
:product-name:
:version: 0.14.1

== Install

Download the https://github.com/knative/client/releases/tag/{knative-version}[latest] Knative Client and add to your `PATH`.

Verify installation by running the command:

[#kn-verify-install]
[.console-input]
[source,bash]
----
kn version
----

The above command will return a response like 

[source,bash,subs="+attributes,macros+"]
----
kn version
Version:      {knative-version}
Build Date:   2020-04-22 08:56:32
Git Revision: c41e9fd
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving {knative-version})
* Eventing
  - sources.knative.dev/v1alpha2 (knative-eventing v0.14.1)
  - eventing.knative.dev/v1alpha1 (knative-eventing v0.14.1)
----

== Create a Knative Service

To create the `greeter` service using `kn` run the following command:

[#kn-create-ksvc-greeter]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service create greeter \
  --namespace kn-cheatsheet \
  --image quay.io/rhdevelopers/knative-tutorial-greeter:quarkus
----

A successful create of the `greeter` service should show a response like 

[source,bash]
[.console-output]
----
Service 'greeter' successfully created in namespace 'kn-cheatsheet'.
Waiting for service 'greeter' to become ready ... OK

Service URL:
http://greeter.kn-cheatsheet.example.com
----

== Create a Knative Service with environment variables

To create the `greeter` service using `kn` run the following command:

[#kn-create-ksvc-greeter]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service create greeter \
  --namespace kn-cheatsheet \
  --image quay.io/rhdevelopers/knative-tutorial-greeter:quarkus \
  --env "MESSAGE_PREFIX=Hola"
----

== Create a Knative Service with Resource Requests and Limits

[#kn-create-ksvc-greeter]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service create greeter \
  --namespace kn-cheatsheet \
  --image quay.io/rhdevelopers/knative-tutorial-greeter:quarkus \
  --limits-cpu 1000m \
  --limits-memory 1024Mi \
  --requests-cpu 250m \
  --requests-memory 64Mi 
----

== Create a Knative Service with Concurrency Target

[#kn-create-ksvc-greeter]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service create greeter \
  --namespace kn-cheatsheet \
  --image quay.io/rhdevelopers/knative-tutorial-greeter:quarkus \
  --concurrency-target 10
----

== List Knative Services

You can list the created services using the command:

[#kn-list-ksvc]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service list --namespace kn-cheatsheet
----

== Update Knative Service

To create a new revision using `kn` is as easy as running another command.

[#run-kn-update-ksvc]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service update greeter --env "MESSAGE_PREFIX=Namaste"
----

== Tagging Knative Services

Assign tag 'latest' and 'stable' to revisions 'echo-v2' and 'echo-v1' respectively

[#run-kn-update-ksvc]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service update greeter \
  --namespace kn-cheatsheet \
  --tag echo-v2=latest \
  --tag echo-v1=stable
----

== Splitting traffic between Knative Revisions

[#run-kn-update-ksvc]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service update greeter \
  --namespace kn-cheatsheet \
  --tag echo-v3=test \
  --traffic test=10,@latest=90
----


[#kn-desc-ksvc]
== Describe Knative Service

To get a description of your Knative Service 

[#run-kn-desc-ksvc]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service describe greeter
----

The describe should show you a short summary of your service : 

[.console-output]
[source,bash]
----
Name:       greeter
Namespace:  kn-cheatsheet
Age:        1m
URL:        http://greeter.kn-cheatsheet.example.com

Revisions:  
  100%  @latest (greeter-twpgf-1) [1] (1m)
        Image:  quay.io/rhdevelopers/knative-tutorial-greeter:quarkus (pinned to 767e2f)

Conditions:  
  OK TYPE                   AGE REASON
  ++ Ready                  34s 
  ++ ConfigurationsReady    34s 
  ++ RoutesReady            34s 
----

== Delete Knative Service

You can also use `kn` to delete the service that were created, to delete the service named `greeter` run the following command:

[#run-kn-delete-ksvc]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn service delete greeter
----

A successful delete should show an output like 

[source,bash]
[.console-output]
----
Service 'greeter' successfully deleted in namespace 'knativetutorial'.
----

<<kn-list-services,Listing services>> you will notice that the `greeter` service no longer exists.

[#kn-revisions]
== Knative Revision Commands

The `kn` revision commands are used to interact with revision(s) of Knative service.

[#kn-revisions-list]
== List Revisions

You can list the available revisions of a Knative service using:

[#run-kn-list-rev]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn revision list
----

The command should show a list of revisions like

[source,bash]
[.console-output]
----
NAME              SERVICE   TRAFFIC   TAGS   GENERATION   AGE   CONDITIONS   READY   REASON
greeter-tjtpm-2   greeter   100%             2            98s   3 OK / 4     True    
greeter-twpgf-1   greeter                    1            11h   3 OK / 4     True    

----

[#kn-revisions-desc]
== Describe Revision

To get the details about a specific revision you can use the command:

[#run-kn-desc-rev]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn revision describe greeter-twpgf-1
----

The command should return a output like

[.console-output]
[source,bash]
----
Name:       greeter-twpgf-1
Namespace:  knativetutorial
Age:        10m
Image:      quay.io/rhdevelopers/kn-cheatsheet-greeter:quarkus (pinned to 767e2f)
Service:    greeter

Conditions:  
  OK TYPE                  AGE REASON
  ++ Ready                  9m 
  ++ ContainerHealthy       9m 
  ++ ResourcesAvailable     9m 
   I Active                 8m NoTraffic

----

[#kn-revisions-delete]
== Delete Revision

To delete a specific revision you can use the command:

[#run-kn-del-rev]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn revision delete greeter-7cqzq
----

The command should return an output like

[.console-output]
[source,bash]
----
Revision 'greeter-7cqzq' successfully deleted in namespace 'knativetutorial'.
----

Now <<kn-invoke-service, invoking service>> will return the response from revision `greeter-6m45j`.

[#kn-routes]
== Knative Route Commands

The `kn` revision commands are used to interact with route(s) of Knative service.

[#kn-routes-list]
== List Routes

[#run-kn-rt-list]
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kn route list
----

The command should return an output like

[.console-output]
[source,bash]
----
NAME      URL                                          AGE   CONDITIONS   TRAFFIC
greeter   http://greeter.knativetutorial.example.com   10m   3 OK / 3     100% -> greeter-zd7jk
----